### ISSUE TITLE
Download JBR

### ISSUE THREAD

**Issue by ForNeVeR** [mfilippov/gradle-jvm-wrapper#25]
Consider I wanna download JetBrains Runtime SDK (e.g. because I want to use JavaFX in my code which isn't included into Coretto).

JetBrains publish the JBR download links in [the Confluence page](https://confluence.jetbrains.com/display/JBR/Release+notes), so we could easily set up the plugin to download the proper JBR SDK builds.

I've tried that, and had the following troubles:

1. Unfortunately, JBR builds are packed in `tar.gz` even on Windows, so your unzip PowerShell script won't work.

   Fortunately, it's easy to fix, since latest builds of Windows 10 include their own `tar` binary by default (yes, seriously!).
2. File name generator doesn't work properly with JetBrains URLs. For example, for URL `https://bintray.com/jetbrains/intellij-jbr/download_file?file_path=jbrsdk-11_0_6-linux-x64-b765.15.tar.gz` it'll think that the file name is `download_file?file_path=jbrsdk-11_0_6-linux-x64-b765.15.tar.gz` which won't work properly.
3. These links use HTTP redirects, and current bash script doesn't call `curl` in a way that follows redirects.

After fixing these minor issues, the plugin will be ready tro download the JBR builds from the currently published links.

**Comment by mfilippov** [comment]
@ForNeVeR Maybe you could send PR :)

**Comment by ForNeVeR** [comment]
I believe this is now possible.
